name: Build Demo
on: workflow_call
jobs:
    Build:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - run: mkdir build && 
                   cd build &&
                   cmake ../ &&
                   make
            - uses: actions/upload-artifact@v3
              with:
                  name: tests
                  path: tests/
