name: Build and Run Tests
on: push
jobs:
    Build_and_Test:
        runs-on: ubuntu-20.04
        steps:
            - uses: .github/workflows/build.yaml
            - uses: .github/workflows/tests.yaml
